[package]
name = "pulldown-cmark"
# Note: This not a valid release, intended to be filled in when it's ready.
version = "0.0.0"
authors = [ "Raph Levien <raph.levien@gmail.com>" ]
license = "MIT"
description = "A pull parser for CommonMark"
repository = "https://github.com/raphlinus/pulldown-cmark"
keywords = ["markdown", "commonmark"]
categories = ["text-processing"]
edition = "2018"

build = "build.rs"

[[bin]]
name = "pulldown-cmark"
required-features = ["getopts"]
doc = false

[dependencies]
bitflags = "1.0"
unicase = "2.2"
getopts = { version = "0.2", optional = true }

[dev-dependencies]
html5ever = "0.20"
lazy_static = "0.2"
regex = "0.2"
tendril = "0.4"

[features]
default = ["getopts"]
gen-tests = []
